//start
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
//ligne 15
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");

console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");

//ligne 5 depuis la fin
console.log("djieodjiz");
console.log("djieodjiz");
console.log("djieodjiz");
//end